services:
  db:
    image: postgres
    restart: always
    environment:
      - POSTGRES_PASSWORD=${PGPASSWORD}
      - POSTGRES_USER=${PGUSER}
    volumes:
      - db-data:/var/lib/postgresql/data/

  app:
    image: denbalogh/yellfest:latest
    depends_on:
      - db
    restart: always
    ports:
      - ${APP_PORT}:${APP_PORT}
    environment:
      - APP_PORT=${APP_PORT}
      - PGPASSWORD=${PGPASSWORD}
      - PGUSER=${PGUSER}
      - PGHOST=db
volumes:
  db-data:
