version: "3"
services:
  db:
    image: postgres
    restart: always
    environment:
      - POSTGRES_PASSWORD=${PGPASSWORD}
      - POSTGRES_USER=${PGUSER}

  app:
    depends_on:
      - db
    build: ./
    ports:
      - ${APP_PORT}:${APP_PORT}
    environment:
      - APP_PORT=${APP_PORT}
      - PGPASSWORD=${PGPASSWORD}
      - PGUSER=${PGUSER}
      - PGHOST=db
